# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Liangc2004
    url: jdbc:mysql://localhost:3306/szu_food_drone?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

# 日志配置（注意：和 spring 同级，不要缩进到 spring 下面）
logging:
  level:
    # 打印请求的基本信息（Controller 日志）
    org.springframework.web: DEBUG

    # 打印 @RequestBody 参数 & 返回值（非常详细）
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: TRACE

    # 打印 JSON 转换的详细信息
    org.springframework.http.converter.json: TRACE